//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;track&quot;:{&quot;title&quot;:&quot;Hello&quot;,&quot;number&quot;:1,&quot;releaseDateTime&quot;:&quot;1998-03-21T09:30:00Z&quot;}}.
        /// </summary>
        public static string TrackJson {
            get {
                return ResourceManager.GetString("TrackJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;page&quot;:2,&quot;pageSize&quot;:3,&quot;totalItems&quot;:1423,&quot;tracks&quot;:[{&quot;title&quot;:&quot;First Track&quot;,&quot;number&quot;:1,&quot;releaseDateTime&quot;:&quot;1998-03-21T09:30:00Z&quot;},{&quot;title&quot;:&quot;Another Track&quot;,&quot;number&quot;:5,&quot;releaseDateTime&quot;:&quot;2009-12-07T11:45:23Z&quot;},{&quot;title&quot;:&quot;Final Track&quot;,&quot;number&quot;:13,&quot;releaseDateTime&quot;:&quot;2014-07-30T17:12:56Z&quot;}]}.
        /// </summary>
        public static string TracksJson {
            get {
                return ResourceManager.GetString("TracksJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;response xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; status=&quot;ok&quot; version=&quot;1.2&quot; xsi:noNamespaceSchemaLocation=&quot;http://api.7digital.com/1.2/static/7digitalAPI.xsd&quot;&gt;&lt;tracks&gt;&lt;page&gt;2&lt;/page&gt;&lt;pageSize&gt;3&lt;/pageSize&gt;&lt;totalItems&gt;1423&lt;/totalItems&gt;&lt;track&gt;&lt;title&gt;First Track&lt;/title&gt;&lt;number&gt;1&lt;/number&gt;&lt;releaseDateTime&gt;1998-03-21T09:30:00Z&lt;/releaseDateTime&gt;&lt;/track&gt;&lt;track&gt;&lt;title&gt;Another Track&lt;/title&gt;&lt;number&gt;5&lt;/number&gt;&lt;releaseDateTime [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TracksXml {
            get {
                return ResourceManager.GetString("TracksXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;response xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; status=&quot;ok&quot; version=&quot;1.2&quot; xsi:noNamespaceSchemaLocation=&quot;http://api.7digital.com/1.2/static/7digitalAPI.xsd&quot;&gt;&lt;track&gt;&lt;title&gt;Hello&lt;/title&gt;&lt;number&gt;1&lt;/number&gt;&lt;releaseDateTime&gt;1998-03-21T09:30:00Z&lt;/releaseDateTime&gt;&lt;/track&gt;&lt;/response&gt;.
        /// </summary>
        public static string TrackXml {
            get {
                return ResourceManager.GetString("TrackXml", resourceCulture);
            }
        }
    }
}
